### ISSUE TITLE
Key Value Pair (Profile input)

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#13]
## Key Value Pair
 
- In UT-Core we're going to support the reading and decoding of a YAML file.
- This will be read into a internal KVP database, which can be accessed by calling the UT-Core
 
E.g run a specific platform test.
 
The configuration file is passed into ut-core via the '--profile' parameter
 
`./run_test --profile xione.de.wifi_configuration.yaml --config xyz.yaml`
 
The testing code would look like this
 
```c
test_radio_count( void )
{
    uint8_t count = wifi_hal_getNumberOfRadios(handle);
    UT_ASSERT_EQUAL_KVP_INT( count, "WifiRadioConfig.NumberOfRadios" );
}
```

But to allow easy debugging and walk-through with the debugger it may be more advisable to write the code like this.

```c
test_radio_count( void )
{
    uint8_t count = wifi_hal_getNumberOfRadios(handle);
    uint8_t expectedCount = UT_KVP_GET_INT( "WifiRadioConfig.NumberOfRadios" );
    UT_ASSERT_EQUAL( count,  expectedCount );
}
```
 
### Function definition
 
- ut_kvp.h
                - Doxygen Comments required
 
## Macro Extensions Expected

`ut_kvp_assert.h`
```c
UT_ASSERT_EQUAL_KVP_BOOL
UT_ASSERT_EQUAL_KVP_INT
UT_ASSERT_STRING_EQUAL_KVP_STRING
UT_ASSERT_FLOAT_EQUAL_KVP_FLOAT
```

## KVP basic module design

`ut_kvp.h`
```c

// ut_kvp.h, header to be expanded as required

#include <std_bool.h>
#include <std_int.h>

typedef enum
{
    UT_KVP_INVALID_ELEMENT=0,
    UT_KVP_BOOL,
    UT_KVP_INT,
    UT_KVP_zSTRING,
    UT_KVP_FLOAT,
}ut_kvp_type_t;

#define UT_KVP_MAX_STRING_ELEMENT_SIZE (256)
#define UT_KVP_MAX_ARRAY_SIZE (32)

typedef struct
{
    kvp_type_t  type;      /*!< Type of the value */
    int    arrayElements;  /*!< number of elements in the array*/
    union
    {
        bool        bValue;       /*!< boolean, true or false using std_bool */
        int           intValue;     /*!< signed int */
        const char  szValue[UT_KVP_MAX_STRING_ELEMENT_SIZE];    /*!< char */
        uint32_t    intArray[UT_KVP_MAX_ARRAY_SIZE];    /*!< element array, using arrayElements as element count */
        float      fValue; /*!< float value */
    }u;
}ut_kvp_value_t;

/**
 * @brief create instance handle to the kvp object
 */
uk_kvp_handle_t *ut_kvp_createInstance( void );

/**
 * @brief destory instance handle to the kvp object
 */
uk_key_instance_t ut_kvp_destoryInstance( uk_kvp_handle_t *pHandle );

/**
 * @brief read kvp file and ready for use
 */
ut_kvp_value_t ut_kvp_read( uk_kvp_handle_t *pHandle, const char *pszKvpFile );

/**
 * @brief Get a key value pair from the passed configuration
 *
 * @param param[in] - Handle to the instance
 * @param key[in] - Zero Terminated String Key
 *
 * @return ut_kvp_value_t  - Returned structure
 * @retval type == UT_KVP_INVALID_ELEMENT if the element is not found
 */
ut_kvp_value_t ut_kvp_get( uk_kpt_handle_t *pHandle, const char *pszKey );

Other possible examples 
...
const char * ut_kvp_getString( uk_kpt_handle_t *pHandle, const char *pszKey );
int ut_kvp_getInt( uk_kpt_handle_t *pHandle, const char *pszKey );
int ut_kvp_getIntFromArray( uk_kpt_handle_t *pHandle, const char *pszKey, uint32_t elementIndex );
int ut_kvp_geLong( uk_kpt_handle_t *pHandle, const char *pszKey );
...
float ut_kvp_getFloat( uk_kpt_handle_t *pHandle, const char *pszKey );
```

`ut_kvp_assert.h`

```c
//Usage for KVP Asserting

#include <uk_kvp.h>

// Macro Setup, will perform type checking
#define UT_KVP_GET_BOOL( key ) \
{ \
    ut_kvp_value_t kvpValue; \
    kvpValue = ut_kvp_get( key ); \
    UT_ASSERT( kvpValue.type == UT_KVP_BOOL ); \
    kvpValue.u.bValue; \
} \

#define UT_KVP_GET_INT( key ) \
{ \
    ut_kvp_value_t kvpValue; \
    kvpValue = ut_kvp_get( key ); \
    UT_ASSERT( kvpValue.type == UT_KVP_INT ); \
    kvpValue.u.intValue; \
} \

//.. Expand as required

#define UT_ASSERT_EQUAL_KVP_BOOL( checkValue, key ) \
{ \
    UT_ASSERT( UT_KVP_GET_BOOL( key ) == checkValue ); \
} \

#define UT_ASSERT_EQUAL_KVP_INT(checkValue, key ) \
{ \
    UT_ASSERT( UT_KVP_GET_INT( key ) == checkValue ); \
} \
```

### Example Usage

```c
//... Expand as required

// Usage of macro
{
    uint16_t freqBand;
    bool enabled;
    ut_kvp_value_t kvpValue;
    UT_ASSERT_EQUAL_KVP_BOOL( true, "WifiRadioConfig.0.Enabled" );
    UT_ASSERT_EQUAL_KVP_INT( 0x1, "WifiRadioConfig.0.FreqBand" );
    enabled = UT_KVP_GET_BOOL( "WifiRadioConfig.0.Enabled" );
    freqBand = UT_KVP_GET_INT( "WifiRadioConfig.0.FreqBand" );
}
```

### Example configuration file from the current codebase, since the file is YAML, comments can be used to document the requirements in the profile. An example of which is below. 
 
e..g → xione.de.yaml

using the find function you should be able todo this under the hood.

`WifiRadioConfig/0/RadioIndex`
`WifiRadioConfig/1/RadioIndex`

```yaml
WifiRadioConfig:
  - RadioIndex: 0 # Unique index for the radio interface
    RadioName: "radio1" # Human-readable name for the radio
    Enabled: true  # Whether the radio is currently active
    FreqBand: 1 # Frequency band (1 = 2.4GHz, 2 = 5GHz)
    AutoChannelEnabled: true # Automatically select the best channel
    Channel: 1
    NumSecondaryChannels: 0
    SecondaryChannelsList: " "
    ChannelWidth: 2
    HwMode: 12 # Hardware mode (e.g., 802.11n, 802.11ac)  
    CsaBeaconCount: 100
    Country: "US"
    DcsEnabled: false
    DtimPeriod: 1
    OperatingClass: 0
    BasicDataTransmitRates: 656
    OperationalDataTransmitRates: 8112
    FragmentationThreshold: 2346
    GuardInterval: 16
    TransmitPower: 100
    BeaconInterval: 100
    RtsThreshold: 2347
    FactoryResetSsid: false
    RadioStatsMeasuringRate: 0
    RadioStatsMeasuringInterval: 0
    CtsProtection: false
    ObssCoex: false
    StbcEnable: false
    GreenFieldEnable: false
    UserControl: 0
    AdminControl: 0
    ChanUtilThreshold: 90
    ChanUtilSelfHealEnable: false
  - RadioIndex: 1
    RadioName: "radio2"
    Enabled: true
    FreqBand: 2
    AutoChannelEnabled: true
    Channel: 40
    NumSecondaryChannels: 0
    SecondaryChannelsList: " "
    ChannelWidth: 1
    HwMode: 169
    CsaBeaconCount: 100
    Country: "US"
    DcsEnabled: false
    DtimPeriod: 1
    OperatingClass: 0
    BasicDataTransmitRates: 656
    OperationalDataTransmitRates: 8112
    FragmentationThreshold: 2346
    GuardInterval: 16
    TransmitPower: 100
    BeaconInterval: 100
    RtsThreshold: 2347
    FactoryResetSsid: false
    RadioStatsMeasuringRate: 0
    RadioStatsMeasuringInterval: 0
    CtsProtection: false
    ObssCoex: false
    StbcEnable: false
    GreenFieldEnable: false
    UserControl: 0
    AdminControl: 0
    ChanUtilThreshold: 90
    ChanUtilSelfHealEnable: false
```

Example suggested yaml files

1. libcyaml (https://github.com/tlsa/libcyaml)

- Schema-Based: libcyaml allows you to define a schema for your YAML data, providing validation and ensuring data integrity as you parse.
- Safety-focused: It's designed with safety in mind, making it a good choice for security-sensitive applications.
- Well-documented: It has good documentation and examples to guide your usage.

2. RapidYAML (ryml) (https://github.com/biojppm/rapidyaml)

- Speed: The primary focus of RapidYAML is speed and efficiency. It's one of the fastest YAML parsers for C/C++.
- Flexible: It provides different parsing options to tailor the process to your needs.
- Lightweight: It has minimal dependencies, making it suitable for embedded systems or resource-constrained environments.

3. A fancy 1.2 YAML and JSON parser/writer. - [https://github.com/pantoniou/libfyaml](https://github.com/pantoniou/libfyaml)

- libfyaml is a C library for working with YAML data (parsing and generating).
- It provides comprehensive support for the latest YAML specifications.
- libfyaml passes the official YAML test suite, ensuring its accuracy and reliability.
- The library emphasizes performance with optimizations to reduce data copies and avoid artificial limitations.
